/*
===========================================
Projeto: Banco de Dados Oficina
Autor: Denis André Ramalho
Descrição: Script de criação do banco de dados Oficina.
===========================================
*/


CREATE DATABASE OFICINA;

USE OFICINA;


CREATE TABLE CLIENTE (
    IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    SEXO ENUM('M', 'F') NOT NULL
);


CREATE TABLE TELEFONE (
    IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('CEL', 'RES', 'COM') NOT NULL,
    NUMERO VARCHAR(30) NOT NULL,
    ID_CLIENTE INT NOT NULL
);


CREATE TABLE MARCA (
    IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
    MARCA VARCHAR(30) NOT NULL UNIQUE
);


CREATE TABLE COR (
    IDCOR INT PRIMARY KEY AUTO_INCREMENT,
    COR VARCHAR(30) NOT NULL UNIQUE
);


CREATE TABLE CARRO (
    IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
    MODELO VARCHAR(30) NOT NULL,
    PLACA VARCHAR(10) NOT NULL UNIQUE,
    ID_CLIENTE INT NOT NULL,
    ID_MARCA INT NOT NULL
);


CREATE TABLE CARRO_COR (
    ID_CARRO INT NOT NULL,
    ID_COR INT NOT NULL
);


/* CHAVE PRIMÁRIA COMPOSTA */

ALTER TABLE CARRO_COR
ADD CONSTRAINT PK_CARRO_COR
PRIMARY KEY (ID_CARRO, ID_COR);


/* CHAVES ESTRANGEIRAS */

ALTER TABLE TELEFONE
ADD CONSTRAINT FK_TELEFONE_CLIENTE
FOREIGN KEY (ID_CLIENTE)
REFERENCES CLIENTE (IDCLIENTE);


ALTER TABLE CARRO
ADD CONSTRAINT FK_CARRO_CLIENTE
FOREIGN KEY (ID_CLIENTE)
REFERENCES CLIENTE (IDCLIENTE);


ALTER TABLE CARRO
ADD CONSTRAINT FK_CARRO_MARCA
FOREIGN KEY (ID_MARCA)
REFERENCES MARCA (IDMARCA);


ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_CARRO_COR_CARRO
FOREIGN KEY (ID_CARRO)
REFERENCES CARRO (IDCARRO);


ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_CARRO_COR_COR
FOREIGN KEY (ID_COR)
REFERENCES COR (IDCOR);
